include: 
  # Start Ollama
  - ollama-runtime/ollama.yaml

  # Download LLMs
  - models/tinydolphin-llm.yaml
  # model + chat model
  - models/tinyllama-llm.yaml

  #- models/phi-llm.yaml
  #- models/orca-mini-7b-llm.yaml
  - models/llama2.yaml
  #- models/llama2-13b.yaml

  # Start GenAI application demos
  - python-dev-environment/app.yaml
  - js-dev-environment/app.yaml

