services:
  # GenAI application
  js-dev-environment:
    entrypoint: ["code-server", "--auth", "none", "--host", "0.0.0.0", "--port", "${JS_APP_TPL_HTTP_PORT}", "/js-dev-environment/workspace"]
    environment: &environment-js
      - JS_APP_TPL_HTTP_PORT=${JS_APP_TPL_HTTP_PORT}
      - XDG_DATA_HOME=/js-dev-environment/.config
      - OLLAMA_BASE_URL=http://ollama-service:11434
    build: &build-js
      context: .
      dockerfile: Dockerfile    
      args:
        - CODER_VERSION=${CODER_VERSION}
        - CODER_ARCH=${CODER_ARCH}
    depends_on:
      ollama-service:
        condition: service_started
    #platform: linux/${LINUX_ARCH}
    volumes: &volumes-js
      - ../js-dev-environment:/js-dev-environment
    ports:
      - ${JS_APP_TPL_HTTP_PORT}:${JS_APP_TPL_HTTP_PORT}

  js-dev-environment-tasks:
    depends_on:
      - js-dev-environment
    entrypoint: ["/js-dev-environment/.tasks/init.sh"]
    environment: *environment-js
    build: *build-js  
    #platform: linux/${LINUX_ARCH}
    volumes: *volumes-js
